export default {
  TrafficSignal: "Traffic Signal",
  ModDefault: "Default",
  Vanilla: "Vanilla",
  SplitPhasing: "Split Phasing",
  ProtectedRightTurns: "Protected Right-Turns",
  ProtectedLeftTurns: "Protected Left-Turns",
  Options: "Options",
  ExclusivePedestrianPhase: "Exclusive Pedestrian Phase",
  Close: "Close",
  Open: "Open",
  Reset: "Reset",
  Save: "Save",
  PleaseSave: "Please save changes before selecting another junction.",
  PleaseSelectJunction: "Please Select a Junction",
  GiveWayToOncomingVehicles: "Give Way to Oncoming Vehicles",
  CustomPedestrianDurationMultiplier: "Pedestrian Phase Duration",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Allow Turning on Red",
  CanaryBuildWarning: "Please note that you are using a canary build, which is more likely to contain game-breaking or save-breaking bugs and is strictly for playtesting only. DO NOT use this build for normal gameplay."
};