export default {
  TrafficSignal: "Traffic Signal",
  ModDefault: "Default",
  Vanilla: "Vanilla",
  SplitPhasing: "Split Phasing",
  ProtectedRightTurns: "Protected Right-Turns",
  ProtectedLeftTurns: "Protected Left-Turns",
  Options: "Options",
  ExclusivePedestrianPhase: "Exclusive Pedestrian Phase",
  Close: "Close",
  Open: "Open",
  Reset: "Reset",
  Save: "Save",
  PleaseSave: "Please save changes before selecting another junction.",
  PleaseSelectJunction: "Please Select a Junction",
  GiveWayToOncomingVehicles: "Give Way to Oncoming Vehicles",
  CustomPedestrianDurationMultiplier: "Pedestrian Phase Duration",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Allow Turning on Red",
  CanaryBuildWarning: "Please note that you are using a canary build, which is more likely to contain game-breaking or save-breaking bugs and is strictly for playtesting only. DO NOT use this build for normal gameplay.",
  CustomPhase: "Custom Phase",
  CustomPhaseEditor: "Custom Phase Editor",
  Phase: "Phase",
  Add: "Add",
  Back: "Back",
  ManualControl: "Manual Control",
  LinkPhase: "Link with next phase",
  UnlinkPhase: "Unlink from next phase",
  PrioritiseTrack: "Prioritise Trams / Trains",
  PrioritisePublicCar: "Prioritise Buses",
  PrioritisePedestrian: "Prioritise Pedestrians",
  TrafficSignGo: "Go",
  TrafficSignYield: "Yield",
  TrafficSignStop: "Stop",
  Adjustments: "Adjustments",
  MinimumDuration: "Minimum Duration",
  MaximumDuration: "Maximum Duration",
  TargetDurationMultiplier: "Target Duration Multiplier",
  LaneOccupiedMultiplier: "Lane Occupied Multiplier",
  IntervalExponent: "Interval Exponent",
  Statistics: "Statistics",
  Timer: "Timer",
  Priority: "Priority",
  LastRun: "Turns Since Last Run",
  CarFlow: "Car Flow",
  LanesOccupied: "Lanes Occupied",
  WeightedWaiting: "Weighted Waiting",
  s: "s"
};
