export default {
  TrafficSignal: "信号灯",
  ModDefault: "默认",
  Vanilla: "原版",
  SplitPhasing: "分向放行",
  ProtectedRightTurns: "右转专用相位",
  ProtectedLeftTurns: "左转专用相位",
  Options: "选项",
  ExclusivePedestrianPhase: "行人专用相位",
  Close: "关闭",
  Open: "打开",
  Reset: "重置",
  Save: "保存",
  PleaseSave: "切换到其他路口前，请先保存当前修改。",
  PleaseSelectJunction: "请选择一个路口",
  GiveWayToOncomingVehicles: "让行对向车辆",
  CustomPedestrianDurationMultiplier: "行人相位时长",
  CustomPedestrianDurationMultiplierSuffix: "倍",
  AllowTurningOnRed: "允许红灯转弯",
  CanaryBuildWarning: "当前为测试版本，可能导致游戏崩溃或存档损坏，仅供试验使用，请勿用于正常游玩。"
};
